# Generated by Django 5.2.7 on 2025-11-09 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20),
        ),
    ]
