# Generated by Django 5.2.7 on 2025-11-09 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0003_alter_payment_due_date_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naas.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'position': 'clerk'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naas.employee')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naas.subscription')),
            ],
            options={
                'db_table': 'pause_request',
            },
        ),
    ]
