# Generated by Django 5.2.7 on 2025-11-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0004_pauserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pause_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naas.employee'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_reason',
            field=models.CharField(blank=True, choices=[('vacation', 'Vacation'), ('financial', 'Financial Hardship'), ('delivery_issues', 'Delivery Issues'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_status',
            field=models.CharField(choices=[('no_request', 'No Request'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no_request', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='PauseRequest',
        ),
    ]
