# Generated by Django 5.2.7 on 2025-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0005_subscription_pause_end_date_subscription_pause_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('all', 'All Channels')], default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='NewsExpress Notification', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
