# Generated by Django 5.2.7 on 2025-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0006_alter_notification_options_notification_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='NewsExpress Notification', max_length=255),
        ),
    ]
